### ISSUE TITLE
Fresh pull, won't load, can't find TikaServerCli

### ISSUE THREAD

**Issue by ntobik** [LexPredict/tika-server#2]
root@imageswarm01:~# docker run -it -p 9998:9998 lexpredict/tika-server
Tika Server Docker Image built Thu Aug 8 03:01:38 UTC 2019
Java Version:
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
Tesseract:
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX
 Found SSE
Tika: 1.20
Config:
<?xml version="1.0" encoding="UTF-8"?>
<properties>
  <parsers>
    
    <parser class="org.apache.tika.parser.DefaultParser">
      <mime-exclude>application/pdf</mime-exclude>
      <parser-exclude class="org.apache.tika.parser.executable.ExecutableParser"/>
    </parser>
    
    <parser class="com.lexpredict.tika.AlterPDFParser">
      <mime>application/pdf</mime>
    </parser>
  </parsers>
</properties>Error: Could not find or load main class org.apache.tika.server.TikaServerCli
root@imageswarm01:~#

Total fresh pull from Docker-latest.  Looks like some dependency is missing

**Comment by mviktorov** [comment]
Looks like I forgot to update TIKA to 1.22 in the Dockerfile.
Could you please try now?

**Comment by ntobik** [comment]
Yup, that was it.  Thanks!
